apiVersion: v1
kind: Service
metadata:
  name: college-club-backend-service
spec:
  selector:
    app: college-club-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
